spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true&useSSL=false
    password: root
    initialSize: 5
